### ISSUE TITLE
UserStory #1: Create form-component for the entry of meals

### ISSUE THREAD

**Issue by aseeba** [aseeba/capstone-project#2]
## Value Statement:

**As a user,** 
**I would like** to plan the day before what I will eat the next day

## Description (Text / Scribble / Wireframe / Design)

<img width="244" alt="Bildschirmfoto 2021-03-09 um 10 50 44" src="https://user-images.githubusercontent.com/71663151/110452427-754faa80-80c5-11eb-915f-967fc5e990cf.png">

## Acceptance Criteria
- [x] Semantically well structured form (don't forget the label)
- [x] Show heading and textareas
- [x] Show placeholder text
- [x] Maximum length in text field: 75 characters
- [x] Set focus fot the active textarea

## ToDos
- [x] Create feature branch
- [x] Create component with styled-components 
- [x] Add component in storybook
- [x] Write component tests
- [x] Add component to the app
- [x] Adjust styles
- [x] Test on mobile and desktop
