### ISSUE TITLE
UserStory #2: Create component for button and page for planned meals, embed local storage

### ISSUE THREAD

**Issue by aseeba** [aseeba/capstone-project#3]
## Value Statement:

**As a user,** 
**I would like** to save the meals I have planned and have the entries in an extra overview on a new page (NextMealsPage).

**As a user,**  
**I don't want** to have to re-enter my meals every time and would like to reuse them from the local storage.

**As a user,** 
**I would like** to go back to input fields and plan a new day.

## Description (Text / Scribble / Wireframe / Design)

<img width="676" alt="Bildschirmfoto 2021-04-19 um 14 00 24" src="https://user-images.githubusercontent.com/71663151/115233119-d2546c80-a117-11eb-9271-24870640fa5f.png">

## Acceptance Criteria
- [x] Local Storage entries are displayed.
- [x] Button should display as block element.
- [x] Button should navigate to the overview where the entries are shown.
- [x] List with entries is shown with 4 items in 2 rows /2 colums
- [x] Items with long entries are displayed with automatic hyphenation (noticeable in long meal descriptions)

## ToDos
- [x] Create feature branch
- [x] Create component with styled-components 
- [x] Add component in storybook
- [x] Write component tests
- [x] Add component to the app
- [x] Adjust styles
- [x] Test on mobile and desktop
