### ISSUE TITLE
UserStory #3: LocalStorage

### ISSUE THREAD

**Issue by aseeba** [aseeba/capstone-project#4]
## Value Statement

As a user, 
I need the possibility to **save the form entries in the browser** so that they are still available after closing.

## Description (Text / Scribble / Wireframe / Design)

<img width="233" alt="Bildschirmfoto 2021-03-09 um 10 51 09" src="https://user-images.githubusercontent.com/71663151/110453128-28b89f00-80c6-11eb-9d42-4acbf6f41d59.png">

## ToDos
- [ ] Create feature branch
- [ ] Add component 
- [ ] Write component tests
- [ ] Add component to the app
- [ ] Test on mobile and desktop
