### ISSUE TITLE
UserStory #3: Save entries with date and switch between daily overviews.

### ISSUE THREAD

**Issue by aseeba** [aseeba/capstone-project#5]
## Value Statement

**As a user, 
I need to** be able to select a date easily so that I can save my meals by date.

**As a user, 
would like to** switch between my daily overviews so that I know what I want to eat or have eaten on the different days.

## Description (Text / Scribble / Wireframe / Design)

<img width="451" alt="Bildschirmfoto 2021-04-19 um 14 11 32" src="https://user-images.githubusercontent.com/71663151/115234352-388dbf00-a119-11eb-9cc3-b3ca7fb7cdf6.png">

## Acceptance Criteria
- [ ] New input field with a date-picker is shown as first input field.
- [ ] A calendar-icon is located on the left side of the input field.
- [ ] The date input is required.
- [ ] After saving the entries, the overviews are displayed with the respective date.
- [ ] Buttons can be used to navigate forwards and backwards through the overviews.

## ToDos
- [ ] Create feature branch
- [ ] Create component with styled-components 
- [ ] Add component in storybook
- [ ] Write component tests
- [ ] Add component to the app
- [ ] Adjust styles
- [ ] Test on mobile and desktop
