### ISSUE TITLE
UserStory #4: Improve usability

### ISSUE THREAD

**Issue by aseeba** [aseeba/capstone-project#8]
## Value Statement

**As a user,
I would like to** have the possibility to overwrite already planned days and do not want to have them twice.

**As a user,
I would like to** have the save button to be active only after an entry has been made in the input fields.

**As a user,
I would like to** have a more precise indication such as "TODAY", "TOMORROW" or "YESTERDAY" displayed instead of the date, so that I can orientate myself more easily.

**As a user,
I need to have** a sorted list by date for all daily overviews.

## Description (Text / Scribble / Wireframe / Design)

<img width="1124" alt="Bildschirmfoto 2021-04-19 um 14 50 58" src="https://user-images.githubusercontent.com/71663151/115239159-b7d1c180-a11e-11eb-91ee-09e447372dd6.png">

## Acceptance Criteria

- [ ] RegEx should be used to validate spaces.

## ToDos
- [ ] Create feature branch
- [ ] Create component with styled-components 
- [ ] Add component in storybook
- [ ] Write component tests
- [ ] Add component to the app
- [ ] Adjust styles
- [ ] Test on mobile and desktop
